#faq_index:
#    path:     /
#    defaults: { _controller: "BoosterBundle:Faq:index" }
#    methods:  GET

#faq_show:
#    path:     /{id}/show
#    defaults: { _controller: "BoosterBundle:Faq:show" }
#    methods:  GET

#faq_new:
#    path:     /new
#    defaults: { _controller: "BoosterBundle:Faq:new" }
#    methods:  [GET, POST]

#faq_edit:
#    path:     /{id}/edit
#    defaults: { _controller: "BoosterBundle:Faq:edit" }
#    methods:  [GET, POST]

#faq_delete:
#    path:     /{id}/delete
#    defaults: { _controller: "BoosterBundle:Faq:delete" }
#    methods:  DELETE
