#society_index:
#    path:     /
#    defaults: { _controller: "BoosterBundle:Society:index" }
#    methods:  GET

#society_show:
#    path:     /{id}/show
#    defaults: { _controller: "BoosterBundle:Society:show" }
#    methods:  GET

#society_new:
#    path:     /new
#    defaults: { _controller: "BoosterBundle:Society:new" }
#    methods:  [GET, POST]

#society_edit:
#    path:     /{id}/edit
#    defaults: { _controller: "BoosterBundle:Society:edit" }
#    methods:  [GET, POST]

#society_delete:
#    path:     /{id}/delete
#    defaults: { _controller: "BoosterBundle:Society:delete" }
#    methods:  DELETE
