transaction_index:
    path:     /
    defaults: { _controller: "BoosterBundle:Transaction:index" }
    methods:  GET

#transaction_show:
#    path:     /{id}/show
#    defaults: { _controller: "BoosterBundle:Transaction:show" }
#    methods:  GET

transaction_new:
    path:     /{id}/new
    defaults: { _controller: "BoosterBundle:Transaction:new" }
    methods:  [GET, POST]

transaction_edit:
    path:     /{id}/edit
    defaults: { _controller: "BoosterBundle:Transaction:edit" }
    methods:  [GET, POST]

#transaction_delete:
#    path:     /{id}/delete
#    defaults: { _controller: "BoosterBundle:Transaction:delete" }
#    methods:  DELETE

